import React from 'react';
import Report from '~/components/dynamic-report/report';
import parseSchema from '~/components/dynamic-report/parseSchema';

describe('报告自动生成', () => {
  it('获取网银报告数据', () => {
    const settings = {
      channel: 'FUDATA_ANALYSIS',
      url: 'fudata/analysisReport',
      urlDesc: '富数分析报告',
      fields: [
        {
          parent: '',
          field: 'data',
          fieldDesc: '报告信息',
          fieldType: 'List',
          tabFlag: '1',
          tabTitleField: 'data.card',
        },
        { parent: 'data', field: 'data.card', fieldDesc: '银行卡号', fieldType: 'String' },
        { parent: 'data', field: 'data.bank', fieldDesc: '银行名称', fieldType: 'String' },
        { parent: 'data', field: 'data.name', fieldDesc: '持卡人姓名', fieldType: 'String' },
        { parent: 'data', field: 'data.type', fieldDesc: '账户类型', fieldType: 'String' },
        { parent: 'data', field: 'data.openDate', fieldDesc: '开卡时间', fieldType: 'LocalDate' },
        { parent: 'data', field: 'data.cashLimit', fieldDesc: '当前余额(储蓄卡，单位：分)', fieldType: 'String' },
        { parent: 'data', field: 'data.balance', fieldDesc: '当前余额(储蓄卡，单位：分)', fieldType: 'BigInteger' },
        {
          parent: 'data',
          field: 'data.consumeLimit',
          fieldDesc: '消费额度(信用卡，单位：分)',
          fieldType: 'BigInteger',
        },
        {
          parent: 'data.bankCardSum.bankCardSummary',
          field: 'data.bankCardSum.bankCardSummary.bankCard',
          fieldDesc: '银行卡号',
          fieldType: 'String',
        },
        {
          parent: 'data',
          field: 'data.usableConsumeLimit',
          fieldDesc: '可用消费额度(信用卡，单位：分)',
          fieldType: 'BigInteger',
        },
        { parent: 'data', field: 'data.userName', fieldDesc: '用户填写姓名', fieldType: 'String' },
        { parent: 'data', field: 'data.userIdCard', fieldDesc: '用户填写身份证', fieldType: 'String' },
        { parent: 'data', field: 'data.userPhone', fieldDesc: '用户填写手机号', fieldType: 'String' },
        { parent: 'data', field: 'data.nameMatch', fieldDesc: '姓名是否一致', fieldType: 'String' },
        { parent: 'data', field: 'data.idCardMatch', fieldDesc: '身份证是否一致', fieldType: 'String' },
        { parent: 'data', field: 'data.averageSalary', fieldDesc: '平均工资', fieldType: 'BigInteger' },
        { parent: 'data', field: 'data.salaryStability', fieldDesc: '工资稳定性水平', fieldType: 'String' },
        { parent: 'data', field: 'data.averageRepaymentPerMonth', fieldDesc: '每月平均还款', fieldType: 'BigInteger' },
        { parent: 'data', field: 'data.foreignConsumeCount', fieldDesc: '外币消费总笔数(6期)', fieldType: 'Integer' },
        { parent: 'data', field: 'data.overdueCount', fieldDesc: '逾期期数(6期)', fieldType: 'Integer' },
        { parent: 'data', field: 'data.overdueAmount', fieldDesc: '逾期金额总和(分)(6期)', fieldType: 'BigInteger' },
        {
          parent: 'data',
          field: 'data.maxSeriesOverdueCount',
          fieldDesc: '最大连续逾期期数(12期)',
          fieldType: 'Integer',
        },
        {
          parent: 'data',
          field: 'data.overdueStatus',
          fieldDesc: '逾期状态列表(12期):0表示正常；1表示逾期',
          fieldType: 'List',
          tabFlag: '1',
        },
        {
          parent: 'data',
          field: 'data.monthSummaries',
          fieldDesc: '每月汇总列表，共12个月（储蓄卡）',
          fieldType: 'List',
        },
        {
          parent: 'data.monthSummaries',
          field: 'data.monthSummaries.month',
          fieldDesc: '月份',
          fieldType: 'YearMonth',
        },
        {
          parent: 'data.monthSummaries',
          field: 'data.monthSummaries.outflowCount',
          fieldDesc: '流出总笔数',
          fieldType: 'Integer',
        },
        {
          parent: 'data.monthSummaries',
          field: 'data.monthSummaries.outflowSumAmount',
          fieldDesc: '流出总金额(分)',
          fieldType: 'BigInteger',
        },
        {
          parent: 'data.monthSummaries',
          field: 'data.monthSummaries.outflowMaxAmount',
          fieldDesc: '最大单笔流出金额',
          fieldType: 'BigInteger',
        },
        {
          parent: 'data.monthSummaries',
          field: 'data.monthSummaries.inflowCount',
          fieldDesc: '流入总笔数',
          fieldType: 'Integer',
        },
        {
          parent: 'data.monthSummaries',
          field: 'data.monthSummaries.inflowSumAmount',
          fieldDesc: '流入总金额(分)',
          fieldType: 'BigInteger',
        },
        {
          parent: 'data.monthSummaries',
          field: 'data.monthSummaries.inflowMaxAmount',
          fieldDesc: '最大单笔流入金额',
          fieldType: 'BigInteger',
        },
        { parent: 'data', field: 'data.interests', fieldDesc: '结息信息列表', fieldType: 'List' },
        { parent: 'data.interests', field: 'data.interests.date', fieldDesc: '日期', fieldType: 'YearMonth' },
        { parent: 'data.interests', field: 'data.interests.amount', fieldDesc: '金额(分)', fieldType: 'BigInteger' },
        { parent: 'data', field: 'data.salaries', fieldDesc: '工资列表', fieldType: 'List' },
        { parent: 'data.salaries', field: 'data.salaries.date', fieldDesc: '日期', fieldType: 'YearMonth' },
        { parent: 'data.salaries', field: 'data.salaries.amount', fieldDesc: '金额(分)', fieldType: 'BigInteger' },
        { parent: 'data', field: 'data.loans', fieldDesc: '第三方借贷', fieldType: 'List' },
        { parent: 'data.loans', field: 'data.loans.organization', fieldDesc: '机构名称', fieldType: 'String' },
        { parent: 'data.loans', field: 'data.loans.repayments', fieldDesc: '还款信息列表', fieldType: 'List' },
        {
          parent: 'data.loans.repayments',
          field: 'data.loans.repayments.date',
          fieldDesc: '日期',
          fieldType: 'LocalDateTime',
        },
        {
          parent: 'data.loans.repayments',
          field: 'data.loans.repayments.amount',
          fieldDesc: '金额(分)',
          fieldType: 'BigInteger',
        },
        { parent: 'data', field: 'data.bills', fieldDesc: '账单（信用卡卡报告字段）', fieldType: 'List' },
        { parent: 'data.bills', field: 'data.bills.billDate', fieldDesc: '账单出账', fieldType: 'LocalDate' },
        { parent: 'data.bills', field: 'data.bills.amount', fieldDesc: '账单金额(单位：分)', fieldType: 'BigInteger' },
        { parent: 'data.bills', field: 'data.bills.limitRate', fieldDesc: '额度使用率', fieldType: 'Float' },
        { parent: 'data.bills', field: 'data.bills.payment', fieldDesc: '实际还款金额(分)', fieldType: 'BigInteger' },
        {
          parent: 'data.bills',
          field: 'data.bills.repaymentRate',
          fieldDesc: '还款率(＝实际还款金额／账单金额)',
          fieldType: 'Float',
        },
        { parent: 'data.bills', field: 'data.bills.consumeCount', fieldDesc: '消费笔数', fieldType: 'Integer' },
      ],
    };
    const data = {
      data: [
        {
          averageRepaymentPerMonth: 0,
          averageSalary: 0,
          balance: 0,
          bank: 'string',
          bills: [{ amount: 0, billDate: 'string', consumeCount: 0, limitRate: 0, payment: 0, repaymentRate: 0 }],
          card: '2072',
          cashLimit: 'string',
          consumeLimit: 0,
          foreignConsumeCount: 0,
          idCardMatch: 'string',
          interests: [{ amount: 0, date: 'string' }],
          loans: [{ organization: 'string', repayments: [{ amount: 0, date: 'string' }] }],
          maxSeriesOverdueCount: 0,
          monthSummaries: [
            {
              inflowCount: 0,
              inflowMaxAmount: 0,
              inflowSumAmount: 0,
              month: 'string',
              outflowCount: 0,
              outflowMaxAmount: 0,
              outflowSumAmount: 0,
            },
          ],
          name: 'string',
          nameMatch: 'string',
          openDate: 'string',
          overdueAmount: 0,
          overdueCount: 0,
          overdueStatus: [0],
          salaries: [{ amount: 0, date: 'string' }],
          salaryStability: 'string',
          type: 'string',
          usableConsumeLimit: 0,
          userIdCard: 'string',
          userName: 'string',
          userPhone: 'string',
        },
        {
          averageRepaymentPerMonth: 0,
          averageSalary: 0,
          balance: 0,
          bank: 'string',
          bills: [{ amount: 0, billDate: 'string', consumeCount: 0, limitRate: 0, payment: 0, repaymentRate: 0 }],
          card: '1118',
          cashLimit: 'string',
          consumeLimit: 0,
          foreignConsumeCount: 0,
          idCardMatch: 'string',
          interests: [{ amount: 0, date: 'string' }],
          loans: [{ organization: 'string', repayments: [{ amount: 0, date: 'string' }] }],
          maxSeriesOverdueCount: 0,
          monthSummaries: [
            {
              inflowCount: 0,
              inflowMaxAmount: 0,
              inflowSumAmount: 0,
              month: 'string',
              outflowCount: 0,
              outflowMaxAmount: 0,
              outflowSumAmount: 0,
            },
          ],
          name: 'string',
          nameMatch: 'string',
          openDate: 'string',
          overdueAmount: 0,
          overdueCount: 0,
          overdueStatus: [0],
          salaries: [{ amount: 0, date: 'string' }],
          salaryStability: 'string',
          type: 'string',
          usableConsumeLimit: 0,
          userIdCard: 'string',
          userName: 'string',
          userPhone: 'string',
        },
      ],
    };

    const wrapper = shallow(<Report settings={parseSchema([settings])[settings.url]} data={data} />);

    expect(wrapper).toMatchSnapshot();
  });

  it('罗马经营数据报告', () => {
    const settings = {
      channel: 'LUOMA_BUSINESS',
      url: 'luoMa/queryBusinessInfo',
      urlDesc: '罗马经营流水信息',
      fields: [
        { parent: '', field: 'data', fieldDesc: '报告信息', fieldType: 'Object' },
        { parent: 'data', field: 'data.createTime', fieldDesc: '报告创建时间', fieldType: 'LocalDateTime' },
        { parent: 'data', field: 'data.updateTime', fieldDesc: '报告更新时间', fieldType: 'LocalDateTime' },
        { parent: 'data', field: 'data.ssn', fieldDesc: '身份证', fieldType: 'String' },
        { parent: 'data', field: 'data.personalInfo', fieldDesc: '个人信息', fieldType: 'Object' },
        { parent: 'data.personalInfo', field: 'data.personalInfo.name', fieldDesc: '姓名', fieldType: 'String' },
        { parent: 'data.personalInfo', field: 'data.personalInfo.idNumber', fieldDesc: '身份证', fieldType: 'String' },
        { parent: 'data', field: 'data.bankCardSum', fieldDesc: '银行卡汇总信息', fieldType: 'Invented' },
        {
          parent: 'data.bankCardSum',
          field: 'data.bankCardSum.bankCardSummary',
          fieldDesc: '银行卡摘要信息',
          fieldType: 'List',
          tabFlag: '1',
          tabTitleField: 'data.bankCardSum.bankCardSummary.bankCard',
        },
        {
          parent: 'data.bankCardSum.bankCardSummary',
          field: 'data.bankCardSum.bankCardSummary.bankCard',
          fieldDesc: '银行卡号',
          fieldType: 'String',
        },
        {
          parent: 'data.bankCardSum.bankCardSummary',
          field: 'data.bankCardSum.bankCardSummary.isValid',
          fieldDesc: '是否有效',
          fieldType: 'String',
        },
        {
          parent: 'data.bankCardSum.bankCardSummary',
          field: 'data.bankCardSum.bankCardSummary.openingBank',
          fieldDesc: '开户行',
          fieldType: 'String',
        },
        {
          parent: 'data.bankCardSum.bankCardSummary',
          field: 'data.bankCardSum.bankCardSummary.submiitTime',
          fieldDesc: '流水提交时间',
          fieldType: 'Date',
        },
        {
          parent: 'data.bankCardSum.bankCardSummary',
          field: 'data.bankCardSum.bankCardSummary.carRelatedSpending',
          fieldDesc: '识别流水总额',
          fieldType: 'Double',
        },
      ],
    };
    const data = {
      id: '5f1a9c054e5cef00017c5c3c',
      data: {
        createTime: '2020-07-23T18:27:39.568',
        updateTime: '2020-07-23T18:27:39.568',
        ssn: '310103198712162061',
        personalInfo: { name: '沈故海', idNumber: '310103198712162061' },
        bankCardSum: {
          bankCardSummary: [
            {
              bankCard: '6222081102003655479',
              carRelatedSpending: 1000000,
              isValid: '1',
              openingBank: '中国工商银行(102100099996)',
              submiitTime: '2020-07-08 10:27:39',
            },
          ],
        },
        bankCardInfo: {
          transOverview: { recent1MSpending: 0, recent3MSpending: 0 },
          carSpendingInfo: [
            {
              averageCarSpending: 233500,
              carSpendingPercent: 1,
              count: 4,
              highestCarPrice: 0,
              midCarSpending: 233500,
              recentDealAmount: 20000,
              recentDealTime: '20200720',
              totalSpending: 934000,
              year: '1',
            },
          ],
        },
        publicData: {
          publicCarInfo: {
            annualTransactionFlowForecast: 677280.01,
            avgSaleTerm: 45,
            earliestSaleTime: '20200105',
            invAmount: 0,
            invCount: 0,
            inventroyAvgCarPrice: 74620,
            inventroyCarPriceRange: '0.0至0.0',
            inventroyMedianCarPrice: 63600,
            maxCarPrice: 0,
            minCarPrice: 0,
            mostRecentSaleTime: '20200720',
            stopManaging: '是',
          },
          saleCircleList: [
            { businessMonth: '201907', meanOfSaleCircle: 0, medOfSaleCircle: 0 },
            { businessMonth: '201908', meanOfSaleCircle: 0, medOfSaleCircle: 0 },
            { businessMonth: '201909', meanOfSaleCircle: 72.98, medOfSaleCircle: 0 },
            { businessMonth: '201910', meanOfSaleCircle: 24.18, medOfSaleCircle: 0 },
            { businessMonth: '201911', meanOfSaleCircle: 0, medOfSaleCircle: 0 },
            { businessMonth: '201912', meanOfSaleCircle: 0, medOfSaleCircle: 0 },
            { businessMonth: '202001', meanOfSaleCircle: 0, medOfSaleCircle: 0 },
            { businessMonth: '202002', meanOfSaleCircle: 0, medOfSaleCircle: 0 },
            { businessMonth: '202003', meanOfSaleCircle: 0, medOfSaleCircle: 0 },
            { businessMonth: '202004', meanOfSaleCircle: 0, medOfSaleCircle: 0 },
            { businessMonth: '202005', meanOfSaleCircle: 0, medOfSaleCircle: 0 },
            { businessMonth: '202006', meanOfSaleCircle: 0, medOfSaleCircle: 0 },
          ],
          dispatchCarList: [
            { businessMonth: '201907', dispatchAmountMonth: 2, dispatchCountMonth: 21.55 },
            { businessMonth: '201908', dispatchAmountMonth: 2, dispatchCountMonth: 15.6 },
            { businessMonth: '201909', dispatchAmountMonth: 1, dispatchCountMonth: 4.05 },
            { businessMonth: '201910', dispatchAmountMonth: 2, dispatchCountMonth: 6.71 },
            { businessMonth: '201911', dispatchAmountMonth: 0, dispatchCountMonth: 0 },
            { businessMonth: '201912', dispatchAmountMonth: 0, dispatchCountMonth: 0 },
            { businessMonth: '202001', dispatchAmountMonth: 0, dispatchCountMonth: 0 },
            { businessMonth: '202002', dispatchAmountMonth: 0, dispatchCountMonth: 0 },
            { businessMonth: '202003', dispatchAmountMonth: 0, dispatchCountMonth: 0 },
            { businessMonth: '202004', dispatchAmountMonth: 0, dispatchCountMonth: 0 },
            { businessMonth: '202005', dispatchAmountMonth: 0, dispatchCountMonth: 0 },
            { businessMonth: '202006', dispatchAmountMonth: 0, dispatchCountMonth: 0 },
          ],
          saleCarList: [
            { amountOfSaledCarMonth: 0, businessMonth: '201907', countOfSaledCarMonth: 2 },
            { amountOfSaledCarMonth: 0, businessMonth: '201908', countOfSaledCarMonth: 2 },
            { amountOfSaledCarMonth: 35.41, businessMonth: '201909', countOfSaledCarMonth: 5 },
            { amountOfSaledCarMonth: 21.03, businessMonth: '201910', countOfSaledCarMonth: 4 },
            { amountOfSaledCarMonth: 0, businessMonth: '201911', countOfSaledCarMonth: 2 },
            { amountOfSaledCarMonth: 0, businessMonth: '201912', countOfSaledCarMonth: 2 },
            { amountOfSaledCarMonth: 0, businessMonth: '202001', countOfSaledCarMonth: 2 },
            { amountOfSaledCarMonth: 0, businessMonth: '202002', countOfSaledCarMonth: 2 },
            { amountOfSaledCarMonth: 0, businessMonth: '202003', countOfSaledCarMonth: 2 },
            { amountOfSaledCarMonth: 0, businessMonth: '202004', countOfSaledCarMonth: 2 },
            { amountOfSaledCarMonth: 10, businessMonth: '202005', countOfSaledCarMonth: 1 },
            { amountOfSaledCarMonth: 1000, businessMonth: '202006', countOfSaledCarMonth: 10 },
          ],
          inventoryCarList: [
            { businessMonth: '201907', invAmountMonth: 30.08, invCountMonth: 4 },
            { businessMonth: '201908', invAmountMonth: 45.68, invCountMonth: 6 },
            { businessMonth: '201909', invAmountMonth: 14.32, invCountMonth: 2 },
            { businessMonth: '201910', invAmountMonth: 0, invCountMonth: 0 },
            { businessMonth: '201911', invAmountMonth: 0, invCountMonth: 0 },
            { businessMonth: '201912', invAmountMonth: 0, invCountMonth: 0 },
            { businessMonth: '202001', invAmountMonth: 0, invCountMonth: 3 },
            { businessMonth: '202002', invAmountMonth: 0, invCountMonth: 2 },
            { businessMonth: '202003', invAmountMonth: 0, invCountMonth: 2 },
            { businessMonth: '202004', invAmountMonth: 0, invCountMonth: 0 },
            { businessMonth: '202005', invAmountMonth: 0, invCountMonth: 0 },
            { businessMonth: '202006', invAmountMonth: 0, invCountMonth: 0 },
          ],
        },
        utime: '20200720',
      },
      createDate: 1595579397551,
    };
    const wrapper = shallow(<Report settings={parseSchema([settings])[settings.url]} data={data} />);

    expect(wrapper).toMatchSnapshot();
  });
});
