import { Response } from '../commonType';
import { I银行账户信息 } from '../types/I银行账户信息';
import { IBankBo } from '../types/IBankBo';

import http from '../httpClient';

/**
 * 查询银行账户列表
 */
export const listPaymentAccount = function (
  params: {
    /** 身份证号 */
    ssn: string;
  },
  config?: { [key: string]: any }
): Promise<Response<Array<I银行账户信息>>> {
  return http.get(`/v1/payment-accounts`, {
    params,
    ...config,
  });
};

/**
 * 查询可用银行列表
 */
export const listPaymentBank = function (
  params: {
    /** 租户 */
    tenant: 'hubenlv';
    /** 支付方式 */
    paymentCategory: 'FASTPAY' | 'GATEWAY' | 'ACCOUNT';
    /** 账户类型 */
    bankAccountType: 'PRIVATE' | 'CORPORATE' | 'PLATFORM';
    /** 交易类型 */
    transactionType: 'TOP_UP' | 'WITHDRAW' | 'CHARGE' | 'PAY' | 'TRANSFER' | 'UNKNOWN';
    /** 银行缩写 */
    bankAcronym?:
    | 'PBOC'
    | 'ABC'
    | 'BOC'
    | 'BOCOM'
    | 'CCB'
    | 'ICBC'
    | 'CEB'
    | 'CGB'
    | 'CMB'
    | 'CMBC'
    | 'CNCB'
    | 'HXB'
    | 'HFB'
    | 'HSB'
    | 'IB'
    | 'PAB'
    | 'PSBC'
    | 'SPDB'
    | 'WEBANK'
    | 'SHRB'
    | 'CBHB'
    | 'CZB'
    | 'SB'
    | 'JZCTB'
    | 'QLCB'
    | 'YIBCB'
    | 'PANJCB'
    | 'SHANGRCB'
    | 'GUIZCB'
    | 'LHCB'
    | 'TZCB'
    | 'NCCB'
    | 'XJKCCB'
    | 'QHCB'
    | 'GXBBWCB'
    | 'NBDHCB'
    | 'WLMQCB'
    | 'BOS'
    | 'GZNYCB'
    | 'LAISCB'
    | 'SMXCB'
    | 'DDCB'
    | 'HBB'
    | 'YANGQCB'
    | 'CGNB'
    | 'HUBCB'
    | 'CHDCB'
    | 'CAOYCB'
    | 'PDSCB'
    | 'HUARONGCB'
    | 'ZHONGYCB'
    | 'MIANYCB'
    | 'NZB'
    | 'DONGYCB'
    | 'GANZCB'
    | 'ZJTLCB'
    | 'TIBETCB'
    | 'QSCB'
    | 'BOG'
    | 'QHDCB'
    | 'DATCB'
    | 'JIUJCB'
    | 'HENGSHUICB'
    | 'TAIACB'
    | 'QUANZCB'
    | 'WHCB'
    | 'XINJCB'
    | 'BENXCB'
    | 'HANDCB'
    | 'ZIGONGCB'
    | 'LPSCB'
    | 'DEYCB'
    | 'XMB'
    | 'WFCB'
    | 'JSCB'
    | 'YTCB'
    | 'ZJMTCB'
    | 'ZZCB'
    | 'HMCCB'
    | 'SUINCB'
    | 'GWCB'
    | 'DALCB'
    | 'LSZCB'
    | 'DAIZCB'
    | 'BOCQ'
    | 'BOTS'
    | 'ZJKCB'
    | 'KFCB'
    | 'JINZCB'
    | 'BOHUIHECB'
    | 'NMGCB'
    | 'BOJ'
    | 'JILCB'
    | 'RIZCB'
    | 'COSTALCB'
    | 'SXJS'
    | 'FJCB'
    | 'JZCB'
    | 'LUZCB'
    | 'SZSCB'
    | 'LIUZCB'
    | 'HBCB'
    | 'GUILCB'
    | 'BAODCB'
    | 'JIAXCB'
    | 'ANSCB'
    | 'XINGTCB'
    | 'NINGBCB'
    | 'YNHTCB'
    | 'BOT'
    | 'HAINCCB'
    | 'ZHHRCB'
    | 'HUZCB'
    | 'WUHCB'
    | 'NANYCB'
    | 'HKBCHINA'
    | 'CSCB'
    | 'LUOYCB'
    | 'BOB'
    | 'SQCB'
    | 'LONGJCB'
    | 'CCAB'
    | 'GSCB'
    | 'GZCB'
    | 'KUNLCB'
    | 'ZAOZCB'
    | 'FUDCB'
    | 'FUSCB'
    | 'BOW'
    | 'YAANCB'
    | 'NXCB'
    | 'XUANKCB'
    | 'QUJCB'
    | 'XACB'
    | 'BSB'
    | 'DGCB'
    | 'CHANGZCB'
    | 'BOCD'
    | 'LSCB'
    | 'LIAOYCB'
    | 'DEZCB'
    | 'TIELCB'
    | 'QDB'
    | 'JXCB'
    | 'HULDCB'
    | 'CANGZCB'
    | 'LANGFCB'
    | 'NANCCB'
    | 'GUIYCB'
    | 'JIZCB'
    | 'BONJ'
    | 'BON'
    | 'ZJCZCB'
    | 'PZHCB'
    | 'SHXCB'
    | 'LSCCB'
    | 'ERDSCB'
    | 'JHCB'
    | 'BOH'
    | 'JINCB'
    | 'JSCJCB'
    | 'FUXCB'
    | 'SUZCB'
    | 'HUAXCB'
    | 'SDRCB'
    | 'NXHHRCB'
    | 'FUSRCB'
    | 'GDNHRCB'
    | 'WUXRCB'
    | 'ZSHRCB'
    | 'AHRCB'
    | 'JXRCB'
    | 'JSRCB'
    | 'GZRCB'
    | 'XZRCB'
    | 'GXRCB'
    | 'SXRCB'
    | 'CDRCB'
    | 'FSSSRCB'
    | 'GYRCB'
    | 'JSJYRCB'
    | 'WUJRCB'
    | 'ZHUHRCB'
    | 'ZJRCB'
    | 'ZJXSRCB'
    | 'BJRCB'
    | 'HNRCB'
    | 'TJRCB'
    | 'KMRCB'
    | 'JSDWRCB'
    | 'TAICRCB'
    | 'HUNRCB'
    | 'HBRCB'
    | 'GUIZRCB'
    | 'FSSDRCB'
    | 'SNXS'
    | 'JSCSRCB'
    | 'KLRCB'
    | 'YNRCB'
    | 'ZJJRCB'
    | 'JMXHRCB'
    | 'FJRCB'
    | 'CZRCB'
    | 'LFRDRCB'
    | 'SHRCB'
    | 'CQRCB'
    | 'NBQZRCB'
    | 'DGRCB'
    | 'MTDTCBCL'
    | 'AUXXLCBCL'
    | 'FRHLCBCL'
    | 'DECBCL'
    | 'CAMTLECBCL'
    | 'UBS'
    | 'HYCBCL'
    | 'BOCXGLC'
    | 'DEDYZCL'
    | 'KPDCB'
    | 'BEUCBCL'
    | 'JYCBLC'
    | 'YXCBLC'
    | 'SCB'
    | 'YLCB'
    | 'NLCCBCL'
    | 'JPSJZCBCL'
    | 'SMCBCL'
    | 'RHCBCL'
    | 'GBSGLCBCL'
    | 'CAFYCBCL'
    | 'ITSBLCBCL'
    | 'HSCB'
    | 'THPGCBCL'
    | 'CXCBLC'
    | 'XMICB'
    | 'NLAZCBCL'
    | 'FRBLCL'
    | 'DEDBAGCL'
    | 'CITICBCL'
    | 'UCBCL'
    | 'DEXDCBCL'
    | 'XHCBCL'
    | 'DHCBCL'
    | 'CITIHK'
    | 'ATRCMCL'
    | 'NLCB'
    | 'JBSKCBCL'
    | 'DEBFLYCB'
    | 'WHCBCL'
    | 'BEFTCBCL'
    | 'FRWMCBCL'
    | 'FRXYCBCL'
    | 'XZCBLC'
    | 'HSBLC'
    | 'NANYANGCB'
    | 'HKBEA'
    | 'DEBDYZCB'
    | 'CHXDCBCL'
    | 'HQCBCL'
    | 'KPMMCB'
    | 'HSBC'
    | 'USACBCL'
    | 'HYCB'
    | 'YLCBCL'
    | 'JPSLCBCL'
    | 'OTHERS'
    | 'CB'
    | 'SOCB'
    | 'MB'
    | 'UCB'
    | 'FB'
    | 'RCC'
    | 'RCB'
    | 'CCC'
    | 'VTB'
    | 'OCCB'
    | 'ORCB'
    | 'ORCCB'
    | 'OCCC'
    | 'ORCC'
    | 'ABC2B'
    | 'BOC2B'
    | 'BOCOM2B'
    | 'CCB2B'
    | 'ICBC2B'
    | 'CEB2B'
    | 'CGB2B'
    | 'CMB2B'
    | 'CMBC2B'
    | 'CNCB2B'
    | 'IB2B'
    | 'PAB2B'
    | 'PSBC2B'
    | 'SPDB2B'
    | 'UNKNOWN';
    /** 支付通道 */
    paymentType?:
    | 'ALLINPAY'
    | 'ALLINPAYFAST'
    | 'BAIXINPAY'
    | 'BAIXINPAYFAST'
    | 'BAOPAY'
    | 'BAOPAYFAST'
    | 'BESTPAY'
    | 'CFCAPAY'
    | 'CHINAGPAY'
    | 'CHINAPAY'
    | 'CJTPAY'
    | 'CMBC'
    | 'FUIOUPAY'
    | 'HFBANK'
    | 'LAKALA'
    | 'HFBC'
    | 'JYTPAY'
    | 'NETEASEPAY'
    | 'LLPAY'
    | 'TENPAY'
    | 'WECHATPAY'
    | 'YEEPAY'
    | 'KFTPAY'
    | 'UNSPAY'
    | 'JDPAY'
    | 'UNIONPAY'
    | 'BOS'
    | 'BOSC'
    | 'UCFPAY'
    | 'XINYAN'
    | 'TJUNIONPAY'
    | 'BILLPAY'
    | 'REAPAL'
    | 'SHBANK'
    | 'CEB'
    | 'TBD';
  },
  config?: { [key: string]: any }
): Promise<Response<Array<IBankBo>>> {
  return http.get(`/v1/payment-banks`, {
    params,
    ...config,
  });
};
